services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Encryption\JWEBuilderFactory:
        public: true

    Jose\Component\Encryption\JWELoaderFactory:
        public: true

    Jose\Component\Encryption\Compression\CompressionMethodManagerFactory: ~
    Jose\Component\Encryption\JWETokenHeaderChecker:
        tags:
            - {'name': 'jose.checker.token_type'}
