services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\Console\JKULoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\X5ULoaderCommand:
        tags:
            - {name: 'console.command'}
