services:
    jose.jwk_set_source.jwkset:
        public: false
        class: 'Jose\Bundle\KeyManagement\DependencyInjection\Source\JWKSetSource\JWKSet'
        tags:
            - {'name': 'jose.jwkset_source'}
