services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jose\Component\Signature\JWSBuilderFactory: ~
    Jose\Component\Signature\JWSLoaderFactory: ~
    Jose\Component\Signature\JWSTokenHeaderChecker:
        tags:
            - {'name': 'jose.checker.token_type'}
