services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\KeyManagement\KeyAnalyzer\KeyAnalyzerManager: ~

    Jose\Component\KeyManagement\KeyAnalyzer\AlgorithmAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }

    Jose\Component\KeyManagement\KeyAnalyzer\UsageAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }

    Jose\Component\KeyManagement\KeyAnalyzer\KeyIdentifierAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }

    Jose\Component\KeyManagement\KeyAnalyzer\NoneAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }

    Jose\Component\KeyManagement\KeyAnalyzer\OctAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }

    Jose\Component\KeyManagement\KeyAnalyzer\RsaAnalyzer:
        tags:
            - { name: 'jose.key_analyzer' }
