services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Bundle\JoseFramework\DataCollector\JoseCollector:
        tags:
            -
                name:     'data_collector'
                template: '@JoseFramework/data_collector/template.html.twig'
                id:       'jose_collector'

    Jose\Bundle\JoseFramework\DataCollector\AlgorithmCollector:
        tags:
          - {name: 'jose.data_collector'}
    Jose\Bundle\JoseFramework\DataCollector\CheckerCollector:
        tags:
          - {name: 'jose.data_collector'}
    Jose\Bundle\JoseFramework\DataCollector\JWECollector:
        tags:
          - {name: 'jose.data_collector'}
    Jose\Bundle\JoseFramework\DataCollector\JWSCollector:
        tags:
          - {name: 'jose.data_collector'}
    Jose\Bundle\JoseFramework\DataCollector\KeyCollector:
        tags:
          - {name: 'jose.data_collector'}
