services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\KeyManagement\JKUFactory:
        arguments:
            - '@Jose\Component\Core\Converter\JsonConverter'
            - '@jose.http_client'
            - '@jose.request_factory'

    Jose\Component\KeyManagement\X5UFactory:
            - '@Jose\Component\Core\Converter\JsonConverter'
            - '@jose.http_client'
            - '@jose.request_factory'
