services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

# ---- New algorithms ----
# These algorithms are out of the main specifications but referenced in
# some WebAuthn documents.
#
# They may be subject to changes.
# ------------------------

    Jose\Component\Encryption\Algorithm\KeyEncryption\A128CTR:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CTR'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A192CTR:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A192CTR'}
    Jose\Component\Encryption\Algorithm\KeyEncryption\A256CTR:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CTR'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP384:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP-384'}

    Jose\Component\Encryption\Algorithm\KeyEncryption\RSAOAEP512:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RSA-OAEP-512'}


    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_16_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-16-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_16_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-16-128'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_64_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-64-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A128CCM_64_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A128CCM-64-128'}

    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_16_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-16-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_16_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-16-256'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_64_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-64-64'}
    Jose\Component\Encryption\Algorithm\ContentEncryption\A256CCM_64_128:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'A256CCM-64-256'}
