services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

# ---- New algorithms ----
# These algorithms are out of the main specifications but referenced in
# some WebAuthn documents.
#
# They may be subject to changes.
# ------------------------
    Jose\Component\Signature\Algorithm\RS1:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'RS1'}

    Jose\Component\Signature\Algorithm\HS1:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'HS1'}
    Jose\Component\Signature\Algorithm\HS256_64:
        tags:
            - {'name': 'jose.algorithm', 'alias': 'HS256/64'}
